[CmdletBinding()]
param(
    [string]$EnvFile = "",
    [string]$PowerShellFile = "",
    [switch]$RefreshLinuxPins
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true

$RootDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if ([string]::IsNullOrWhiteSpace($EnvFile)) {
    $EnvFile = Join-Path -Path $RootDir -ChildPath "install/versions.env"
}
if ([string]::IsNullOrWhiteSpace($PowerShellFile)) {
    $PowerShellFile = Join-Path -Path $RootDir -ChildPath "install/versions.ps1"
}

if ($RefreshLinuxPins) {
    if (-not (Get-Command -Name bash -ErrorAction SilentlyContinue)) {
        throw "bash is required for -RefreshLinuxPins."
    }

    $linuxScript = Join-Path -Path $RootDir -ChildPath "scripts/bump-versions.sh"
    if (-not (Test-Path -LiteralPath $linuxScript)) {
        throw "Could not find script: $linuxScript"
    }

    & bash $linuxScript
    if ($LASTEXITCODE -ne 0) {
        throw "scripts/bump-versions.sh failed with exit code $LASTEXITCODE"
    }
}

if (-not (Test-Path -LiteralPath $EnvFile)) {
    throw "Versions env file not found: $EnvFile"
}

$versions = [ordered]@{}
foreach ($line in Get-Content -LiteralPath $EnvFile) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
        continue
    }

    if ($trimmed -notmatch "^([A-Za-z0-9_]+)=(.*)$") {
        throw "Could not parse line in ${EnvFile}: $line"
    }

    $key = $Matches[1]
    $value = $Matches[2]
    $versions[$key] = $value
}

$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$output = New-Object System.Collections.Generic.List[string]
$output.Add("# Auto-generated by scripts/bump-versions.ps1")
$output.Add("# $timestamp")
$output.Add("")
$output.Add('$DotfilesVersions = [ordered]@{')

foreach ($entry in $versions.GetEnumerator()) {
    $escaped = $entry.Value.Replace("'", "''")
    $output.Add("    $($entry.Key) = '$escaped'")
}

$output.Add("}")
$output.Add("")
$output.Add("return `$DotfilesVersions")

Set-Content -LiteralPath $PowerShellFile -Value $output -Encoding utf8NoBOM

Write-Host "Updated $PowerShellFile from $EnvFile"
